//
// Generated file, do not edit! Created by nedtool 5.5 from VoicePacket.msg.
//

#ifndef __VOICEPACKET_M_H
#define __VOICEPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>VoicePacket.msg:4</tt> by nedtool.
 * <pre>
 * //消息文件
 * //定义数据包结构
 * message VoicePacket
 * {
 *     int source_id;//源站
 *     int aim_id;//目的站
 *     double send_time; //该数据包发送的时间
 * }
 * </pre>
 */
class VoicePacket : public ::omnetpp::cMessage
{
  protected:
    int source_id;
    int aim_id;
    double send_time;

  private:
    void copy(const VoicePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VoicePacket&);

  public:
    VoicePacket(const char *name=nullptr, short kind=0);
    VoicePacket(const VoicePacket& other);
    virtual ~VoicePacket();
    VoicePacket& operator=(const VoicePacket& other);
    virtual VoicePacket *dup() const override {return new VoicePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource_id() const;
    virtual void setSource_id(int source_id);
    virtual int getAim_id() const;
    virtual void setAim_id(int aim_id);
    virtual double getSend_time() const;
    virtual void setSend_time(double send_time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VoicePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VoicePacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __VOICEPACKET_M_H

